Cleaning & Improvements ✨ 	modified:   bin/applet 	modified:   bin/colorscheme 	modified:   dunst/dunstrc 	modified:   nvim/keybindings.lua 	modified:   nvim/pkg/colorscheme.lua 	deleted:    nvim/pkg/dashconfig.lua 	modified:   nvim/plugins.lua 	modified:   picom/picom.conf 	modified:   polybar/bars.ini 	modified:   polybar/config.ini

diff --git a/bin/applet b/bin/applet
--- a/bin/applet
+++ b/bin/applet
@@ -5,23 +5,29 @@
 
 applet_path=$HOME/.dotfiles/applets/
 
+options=`ls -d $applet_path/*/ | sed "s#$applet_path##g" | tr "/" " "`
+#| tr "\n" " "`
 Help()
 {
    # Display Help
    echo "applet.sh - Applet Launcher Interface"
-   echo "  Runs selected applet"
+   echo "──────────────────────────────────────────────"
+   echo "Runs selected applet"
    echo
    echo "Syntax: [-r]"
-   echo
    echo "Options:"
-   echo "-h/--help          Prints this menu."
-   echo "-r/--run \$app      Runs selected applet"
+   echo "┌────────────────────────────────────────────┐"
+   echo "│ -h/--help          Prints this menu.       │"
+   echo "│ -r/--run \$app      Runs selected applet    │"
+   echo "└────────────────────────────────────────────┘"
+   echo " Applets:"
+   echo " `echo $options`"
    echo
 }
 
 Run()
 {
-    sh $applet_path/$app/launch.sh
+    sh $applet_path/$app/launch.sh 2>/dev/null
 }
 
 if [[ "$#" -eq 0 ]]; then
@@ -29,21 +35,23 @@ if [[ "$#" -eq 0 ]]; then
     exit
 fi
 for arg in $@;do
-    if   [[ "$arg" = "-h" ]] || [[ "$arg" = "--help" ]]; then
+    if   [ "$arg" = "-h" ] || [ "$arg" = "--help" ]; then
         Help
         exit
     elif [[ $run = true ]]; then 
         app=$arg
-        if [[ "$(find $applet_path/$app 2>/dev/null)" = "" ]]; then
-            echo -e "Error: No such applet at applet directory" 1>&2
-            exit
-        fi
-    elif [[ "$arg" = "-r" ]] || [[ "$arg" = "--run" ]]; then 
+        case "$options" in 
+          *$app*)
+           Run
+           exit
+           ;;
+        esac
+        echo "error: Applet was not found." 1>&2
+    elif [ "$arg" = "-r" ] || [ "$arg" = "--run" ]; then 
         run=true
     else
         echo -e "Error: Invalid arguments" 1>&2
         exit
     fi 
 done
-Run
 
