Rebase

diff --git a/bin/dotfetch b/bin/dotfetch
--- a/bin/dotfetch
+++ b/bin/dotfetch
@@ -1,14 +1,48 @@
 #! /bin/bash
-# Restarts all graphical services while updating their values
+#******************************************************************************
+#
+# * File: dotfetch
+#
+# * Author:  Umut Sevdi
+# * Created: 08/20/22
+# * Description: A script that updates the configuration files and restarts 
+# the i3wm
+#*****************************************************************************
 
-cd $HOME/.config
-rm -rf i3 kitty polybar gtk conky
-cp -r $HOME/.dotfiles/conky/ $HOME/.config/conky/
-cp -r $HOME/.dotfiles/gtk/ $HOME/.config/gtk/
-cp -r $HOME/.dotfiles/i3/ $HOME/.config/i3/
-cp -r $HOME/.dotfiles/kitty $HOME/.config/kitty
-cp -r $HOME/.dotfiles/polybar $HOME/.config/
-cp -r $HOME/.dotfiles/.bashrc $HOME/.bashrc
-sudo cp $HOME/.dotfiles/.bashrc /root/.bashrc
+Help()
+{
+   # Display Help
+   echo "dotfetch - Dotfile Fetcher"
+   echo "  Updates config files and restarts the window manager"
+   echo
+   echo "Syntax: [-r]"
+   echo
+   echo "Options:"
+   echo "-h/--help      Prints this menu."
+   echo "-r/--root      Also updates root user's .bashrc"
+   echo
+}
 
-i3 restart
+Fetch()
+{
+    cd $HOME/.config
+    rm -rf $HOME/.config/autostart/
+    cp -r $HOME/.dotfiles/autostart/ $HOME/.config/
+    cp -r $HOME/.dotfiles/bookmarks $HOME/.config/gtk-3.0/
+    cp -r $HOME/.dotfiles/bashrc $HOME/.bashrc
+    i3-msg restart
+    colorscheme -r
+}
+
+for arg in $@;do
+    if   [ $arg = -h ] || [ $arg = --help ]; then
+        Help
+        exit
+    elif [ $arg = -r ] || [ $arg = --root ]; then 
+        root=true
+    else
+        echo -e "Error: Invalid arguments" 1>&2
+        exit
+    fi 
+done
+Fetch
