Release Update

diff --git a/bin/dotfetch b/bin/dotfetch
--- a/bin/dotfetch
+++ b/bin/dotfetch
@@ -1,6 +1,25 @@
 #! /bin/bash
-# Restarts all graphical services while updating their values
+# dotfetch.sh - Restart and update your configs
+# @umutsevdi 
+#   A script that updates the config files and restarts i3wm
+# @requires i3
 
+Help()
+{
+   # Display Help
+   echo "dotfetch - Dotfile Fetcher"
+   echo "  Updates config files and restarts the window manager"
+   echo
+   echo "Syntax: [-r]"
+   echo
+   echo "Options:"
+   echo "-h/--help      Prints this menu."
+   echo "-r/--root      Also updates root user's .bashrc"
+   echo
+}
+
+Fetch()
+{
 cd $HOME/.config
 rm -rf i3 kitty polybar gtk-3.0 conky awesome
 cp -r $HOME/.dotfiles/conky/ $HOME/.config/conky/
@@ -9,9 +28,24 @@ cp -r $HOME/.dotfiles/i3/ $HOME/.config/i3/
 cp -r $HOME/.dotfiles/kitty $HOME/.config/kitty
 cp -r $HOME/.dotfiles/polybar $HOME/.config/
 cp -r $HOME/.dotfiles/.bashrc $HOME/.bashrc
-cp -r $HOME/.dotfiles/awesome $HOME/.config/awesome
-if [[ "$1" = "--root" ]]; then
+if [[ "$ROOT" = "t" ]]; then
     sudo cp $HOME/.dotfiles/.bashrc /root/.bashrc
 fi
 i3-msg restart
-notify-send 'i3 Window Manager' 'WM has been restarted with updated configurations' --app-name="Resize Window" --icon=window_list --category='presence'
+notify-send 'i3 Window Manager' 'WM has been restarted with updated configurations' \
+    --app-name="Resize Window" --icon=window_list --category='presence'
+}
+
+for arg in $@;do
+    if   [[ "$arg" = "-h" ]] || [[ "$arg" = "--help" ]]; then
+        Help
+        exit
+    elif [[ "$arg" = "-r" ]] || [[ "$arg" = "--root" ]]; then 
+        ROOT="t"
+    else
+        echo -e "Error: Invalid arguments" 1>&2
+        exit
+    fi 
+done
+Fetch
+
diff --git a/bin/pickwp b/bin/pickwp
--- a/bin/pickwp
+++ b/bin/pickwp
@@ -1,16 +1,78 @@
-#! /bin/bash
-# Randomly picks a wallpaper from $HOME/.dotfiles/wallpapers
-# Selects a different wallpaper each time
-# Applies the wallpaper to all monitors
+#!/bin/bash
+# pickwp.sh - Wallpaper picker
+# @umutsevdi 
+# A script that randomly picks a wallpaper from a directory.
+# Selects a different wallpaper on each use.
+# Default path is $HOME/Pictures/wallpapers/ can be configured with --config
+# @requires nitrogen
 
-IMG_PATH="$HOME/.dotfiles/wallpapers/$(ls $HOME/.dotfiles/wallpapers | shuf -n 1)"
-OLD_PATH=$(cat /tmp/pickwp_img)
-while [ "$IMG_PATH" = "$OLD_PATH" ]; do
-    IMG_PATH="$HOME/.dotfiles/wallpapers/$(ls $HOME/.dotfiles/wallpapers | shuf -n 1)"
+if ! command -v nitrogen &> /dev/null ; then
+    sudo dnf install nitrogen
+fi
+
+# Default wallpaper search path
+SEARCH_PATH="$HOME/Pictures/wallpapers"
+# Default monitor count
+HEAD=2
+
+Help()
+{
+   # Display Help
+   echo "pickwp - Wallpaper Picker"
+   echo "  Picks a random wallpaper from your wallpaper directory. Does not"
+   echo "repeat same wallpaper twice" 
+   echo
+   echo "Syntax: [-h/c|m]"
+   echo
+   echo "Options:"
+   echo "-h/--help            Prints this menu."
+   echo "-m/--monitor \$COUNT  The number of monitors to change."
+   echo "-c/--config \$DIR     Picks wallpaper from custom directory."
+   echo
+}
+
+Pick()
+{
+    # Check if directory exists
+    if [[ ! -d $SEARCH_PATH ]]; then
+        echo "Error: Wallpaper directory $SEARCH_PATH does not exist" 1>&2
+        exit
+    fi
+
+    IMG_PATH="$SEARCH_PATH/$(ls $SEARCH_PATH/ | shuf -n 1  2> /dev/null)"
+    OLD_PATH=$(cat /tmp/pickwp_img  2> /dev/null)
+
+    while [ "$IMG_PATH" = "$OLD_PATH" ]; do
+        IMG_PATH="$SEARCH_PATH/$(ls $SEARCH_PATH/ | shuf -n 1  2> /dev/null)"
+    done
+
+    echo $IMG_PATH > /tmp/pickwp_img
+
+    for (( i=0; i < $HEAD; i++ )); do 
+        nitrogen --set-scaled --head=$i $IMG_PATH --save
+    done
+}
+
+for arg in $@; do
+    if [[ $GET_HEAD = "t" ]]; then
+        HEAD=$arg
+        GET_HEAD=""
+    elif [[ "$arg" = "-h" ]] || [[ "$arg" = "--help" ]]; then
+        Help
+        exit
+    elif [[ "$arg" = "-c" ]] || [[ "$arg" = "--config" ]]; then
+        GET_DIR="t"
+    elif [[ "$GET_DIR" = "t" ]]; then
+        SEARCH_PATH=$arg
+        Pick
+        exit
+    elif [[ "$arg" = "-m" ]] || [[ "$arg" = "--monitor" ]]; then
+        GET_HEAD="t" 
+    else
+        echo -e "Error: Invalid arguments" 1>&2
+        exit
+    fi
 done
-echo $IMG_PATH > /tmp/pickwp_img
-for (( i=0; i < 2; i++ )); do 
-    nitrogen --set-scaled --head=$i $IMG_PATH --save
-done
 
-
+# If there are no arguments pick from default directory
+Pick
